### ISSUE TITLE
 itsatrap incorrectly loads 3rd party tracker

### ISSUE THREAD

**Issue by rbillings** [mozilla/ff-tool#108]
Testing with new FF Shavar profiles, opening the itsatrap page shows "a simulated third-party tracker was incorrectly loaded" upon initial display that switches to correctly loaded with a page refresh. 

1. open https://itisatrap.org/firefox/its-a-tracker.html using Nightly and a Shavar list profile
2. refresh the page

This repros consistently with new and existing FF profiles with a variety of prefs. Creating a new profile using the profile manager shows the error but does NOT load correctly with a page refresh.

This does not repro with profiles created outside of ff-tool, nor for manually created profiles that have a homepage set to something other than itsatrap. See more details in bug 1351410.

**Comment by cloud-services-qa** [comment]
Hi Rebecca!

If you have time can we sync up on this on Mon. Or Tues.?  I'll try to repro first but may help to have u walk me thru.  Want to see if I can fix right away.

Thank you!

Pe 7 apr. 2017, la 11:29, Rebecca Billings <notifications@github.com> a scris:

**Comment by rbillings** [comment]
This is an existing issue, and is almost certainly related to things loading in the background- which is why it changes to a correct status after a refresh. This isn't worth a lot of time to dive into to fix, so I'm closing this issue.
