### ISSUE TITLE
Add ability to list profiles

### ISSUE THREAD

**Issue by rpappalax** [mozilla/ff-tool#110]

**Comment by pdehaan** [comment]
How should this work? Just list the locally installed profiles? Or should we try and detect globally installed profiles?

**Comment by rpappalax** [comment]
I was thinking locally in <ff-tool root dir>/.cache/profiles/  and just list them out.  Otherwise, it's hard to know what to choose.  It would be useful to also allow the user to list them, then up-arrow to the one they want.

**Comment by pdehaan** [comment]
Sounds simple enough. You thinking just some basic `ls -l` to get directory names for the _temp/profiles directory? Or something more complex?

My only concern would be users getting oodles of auto-generated profile names returned. A la:

```sh
➜  profiles git:(dev) $ ls -l

total 0
drwx------  54 pdehaan  staff  1836 Jun  3  2016 fftool.5dmZcP
drwx------   4 pdehaan  staff   136 May 26  2016 fftool.B9h1rk
drwx------  52 pdehaan  staff  1768 Jun  2  2016 fftool.D2dLX9
drwx------  55 pdehaan  staff  1870 Jun  2  2016 fftool.PdqJwI
drwx------  51 pdehaan  staff  1734 Jun  2  2016 fftool.WTsa9P
drwx------  52 pdehaan  staff  1768 May 25  2016 fftool.bbVM9B
drwx------  50 pdehaan  staff  1700 Jun 30  2016 fftool.mPyWLo
drwx------  52 pdehaan  staff  1768 Jun  2  2016 fftool.tMsyab
```
