### ISSUE TITLE
Tweak windows paths to use a .cache/profiles instead of %APPDATA

### ISSUE THREAD

**Issue by pdehaan** [mozilla/ff-tool#53]
Windows profile path should behave no differently than OSX/Linux, for consistency.
Only the binary for Windows needs to be installed globally in C:/Program Files/

**Comment by rpappalax** [comment]
seems like I got this:
https://github.com/rpappalax/ff-tool/blob/dev/fftool/__init__.py#L24-L32
but I'll close once we verify that it's actually working!

**Comment by rpappalax** [comment]
we just needed to set it back the way it was.
