### ISSUE TITLE
Migrate to github.com/mozilla

### ISSUE THREAD

**Issue by pdehaan** [mozilla/ff-tool#65]
Not sure if we can just transfer this over to the mozilla-services org: https://github.com/organizations/mozilla-services/

**Comment by rpappalax** [comment]
I'll see if there's any further cleanup needed, then we can create a proj in mozilla-services.

**Comment by rpappalax** [comment]
Let's do this after issues #76 & #90 land

**Comment by rpappalax** [comment]
@pdehaan now that we're fx-test, wondering if this would make more sense in https://github.com/mozilla?  or https://github.com/mozilla-services?

**Comment by rpappalax** [comment]
transferred to mozilla
