### ISSUE TITLE
Throw warning if specifying same pref in 2 sections

### ISSUE THREAD

**Issue by rpappalax** [mozilla/ff-tool#83]

**Comment by pdehaan** [comment]
We should try and figure out whether to throw errors/warnings versus just overwriting one pref with a newer one.
Currently I'm leaning towards just merging the prefs and overwriting, but I can be convinced either way..

**Comment by rpappalax** [comment]
hmm, I  agree if there was an obvious hierarchy to this.  For example, a pref specified in a child sub directory would overwrite one specified in a parent directory.  
The only case I'd be less sure of would be if someone accidentally overwrote the same pref in the same pref file.  Thoughts @pdehaan?

**Comment by pdehaan** [comment]
I don't know what a _hierarchy_ is here. We're just specifying a bunch of directories on a command line.
So we're just going to import your prefs based on the order that you specify them on the command line.
For example, if you specify `-p apples -p apples/e2e-test`, then it will probably overwrite anything in "apples" with any conflicts in "apples/e2e-test".
